### ISSUE TITLE
packaged version has amnesia

### ISSUE THREAD

**Issue by dveditz** [fwenzel/firekey#11]
(Hope this is the correct repo.)  The packaged version of Firekey on marketplace.firefox.com will accept a new account and start showing codes, but when you re-launch the app the UI just shows the Firekey banner at the top. Account is gone, and even the "+" button to add new accounts is gone. There are no usable controls at all, the only thing you can do is close the app.

**Comment by fwenzel** [comment]
That's not cool. Will look into this tomorrow when I am back. Sorry about that

**Comment by fwenzel** [comment]
I fixed that for the hosted version in 611f10c, which I just now cherry picked into the packaged app and that fixes it as well. I will package and update the marketplace version.

**Comment by fwenzel** [comment]
Version 1.1 uploaded to the Marketplace, awaiting review now. Thanks for your patience :)

**Comment by fwenzel** [comment]
Updated version is live
