### ISSUE TITLE
Add a way to remove an account

### ISSUE THREAD

**Issue by theres-waldo** [fwenzel/firekey#12]
Accounts can become obsolete for various reasons. It would be good to have a way of removing one.

**Comment by fwenzel** [comment]
A long click (or press if you're on your phone) should show a Delete button. Try it out :)

**Comment by fwenzel** [comment]
(and if it does not work, by all means let me know)

**Comment by theres-waldo** [comment]
Yup, that does work, thanks. On a phone I probably would've tried that, but it didn't occur to me to try long-clicking on desktop :)

**Comment by fwenzel** [comment]
Hm yeah not the best UI for desktop, I admit!
