### ISSUE TITLE
Firekey keeps refreshing even when hidden

### ISSUE THREAD

**Issue by gabrielesvelto** [fwenzel/firekey#14]
While doing battery-life analysis on my Firefox OS phone I noticed that Firekey kept updating its display even when it's hidden, slowly draining the battery. I've got a WIP patch that fixes this by disabling refresh as long as the app/page is hidden.

**Comment by fwenzel** [comment]
Ooooo great find and sorry about that. I did not know that FxOS would keep rendering the app while it's invisible.

**Comment by gabrielesvelto** [comment]
The app is not being rendered obviously, but the timer is still ticking and its associated code runs which prevents the phone from entering deep sleep states and thus slowly drains the battery over time.
