### ISSUE TITLE
Too easy to delete account

### ISSUE THREAD

**Issue by hwine** [fwenzel/firekey#7]
At least on a flame running FxOS 2.1 -- if you "long press" to display the delete button, at a location where the button will appear, the "button up" from the long press is also considered the "button up" from the delete button. Poof! Account deleted on one action.

I don't get the same behavior in the hosted webapp, so this may be unique to FxOS. (Although, on Android KK, I couldn't get any delete button to appear.)

**Comment by fwenzel** [comment]
ooooh, that's terrible.

I'm gonna be honest I really don't like the long press code I have there and am considering a different UI action for this kind of thing anyway. Just haven't come up with a better one yet.

**Comment by fwenzel** [comment]
Also, apologies that happened :(

**Comment by fwenzel** [comment]
Fixed in the Ember-based version. Will release that one soon (have to figure out how to auto-push to github pages first ;))
