### ISSUE TITLE
Does not work offline

### ISSUE THREAD

**Issue by inscriber** [fwenzel/firekey#9]
If I start the application without an internet connection I get a "Firekey requires an Internet connection."

**Comment by fwenzel** [comment]
Yeah that's true. Sorry about that. There are two things I can/would like to do:

1) make a new version of the app that is hosted and uses a ServiceWorker for offline support. This will only work on very new versions of modern browsers so far, but support is coming to FxOS.
2) put a packaged version of the app in the FxOS marketplace.

Where/how do you use it?

**Comment by inscriber** [comment]
I use the version in FxOS marketplace. My device only has wifi for data connectivity so I run into this offline issue a lot.

**Comment by fwenzel** [comment]
Now it does!

There's a Firefox OS packaged app on the Markteplace: https://marketplace.firefox.com/app/firekey/

And the new version hosted on https://firekey.org uses a ServiceWorker on browsers that support that technology. (Which is currently Chrome and Firefox desktop version 43).
